name: portfolio

services:
  mailpit:
    container_name: portfolio-mailpit
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - mailpitdata:/data
    ports:
      - '8025:8025'
      - '1025:1025'
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - portfolio-network

volumes:
  mailpitdata:
    name: portfolio-mailpitdata

networks:
  portfolio-network:
    name: portfolio
